runtime: nodejs16
env: standard

service_account: team2-516@rice-comp-539-spring-2022.iam.gserviceaccount.com

handlers:
- url: /(.*\.(json|ico|js|png|jpg|jpeg|css|svg|gif|map))$
  static_files: build/\1
  upload: build/(.*\.(json|ico|js|png|jpg|jpeg|css|svg|gif|map))$
  secure: always

- url: /.*
  static_files: build/index.html
  upload: build/index.html
  secure: always
